langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install: raco pkg install --deps search-auto $TRAVIS_BUILD_DIR/trivial

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
 - raco setup --check-pkg-deps trivial
 - raco test $TRAVIS_BUILD_DIR/trivial
 - raco test $TRAVIS_BUILD_DIR/test

#after_success:
# - raco pkg install --deps search-auto cover
# - raco pkg install --deps search-auto cover-coveralls
# - raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage -b .
